org: tmetsoft
app: logis
service: logis-usrv-user-manager
frameworkVersion: ~4.x.x

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  timeout: 29
  memorySize: 512
  stage: dev
  logRetentionInDays: ${file(./slsBuildScript.js):logRetentionInDays}
  deploymentBucket:
    name: ${ssm:/${self:custom.stage}/GL/SERVERLESS_BUCKET}
  httpApi:
    cors: true
    disableDefaultEndpoint: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - cognito-idp:*
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:cognito-idp:us-east-1:"
                - "Ref": "AWS::AccountId"
                - ":userpool/"
                - "Ref": "LogisUserPool"
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
            - lambda:GetFunction
            - lambda:EnableReplication
          Resource: "arn:aws:lambda:${self:custom.region}:${aws:accountId}:function:*"
  environment:
    NODE_OPTIONS: "--enable-source-maps"
    STAGE: ${self:provider.stage}
    POOL_ID:
      Ref: LogisUserPool
build:
  esbuild:
    false
    # bundle: true
    # minify: true
    # platform: node
    # target: node20
    # sourcemap: true
    # # packages: external
    # # plugins: esbuild-plugins.js
    # external:
    #   - "@aws-sdk/*"
    # packager: pnpm
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, "us-east-1"}
  prefix: /${self:provider.stage}/${self:service}
  resourcesPrefix: ${self:provider.stage}-${self:service}
  esbuild:
    bundle: true
    minify: true
    platform: node
    target: node22
    sourcemap: true
    # packages: external
    # plugins: esbuild-plugins.js
    external:
      - "@aws-sdk/*"
    packager: pnpm
  buildVars: ${file(./slsBuildScript.js):slsBuild}
  resources:
    certificateName: ${ssm:/${self:custom.stage}/GL/LOGIS_CERTIFICATE_NAME}
    domainName: ${ssm:/${self:custom.stage}/GL/LOGIS_DOMAIN_NAME}
    fromEmail: ${self:custom.buildVars.fromEmail}
    emailSesArn: ${self:custom.buildVars.emailSesArn}
    customClaimsArn: ${self:custom.buildVars.customClaimsArn}
  customDomain:
    http:
      domainName: ${self:custom.resources.domainName}
      basePath: user
      # stage: ${self:provider.stage}
      endpointType: REGIONAL
      certificateName: ${self:custom.resources.certificateName}
      createRoute53Record: false
  CognitoAddCustomAttributes:
    CognitoUserPoolIdOutputKey: "LogisUserPoolId"
    CognitoUserPoolClientIdOutputKey: "LogisUserClientId"
    CustomAttributes:
      - AttributeDataType: String
        DeveloperOnlyAttribute: False
        Mutable: True
        Name: "status"
        Required: False
      - AttributeDataType: String
        DeveloperOnlyAttribute: False
        Mutable: True
        Name: "role"
        Required: True
      - AttributeDataType: String
        DeveloperOnlyAttribute: False
        Mutable: True
        Name: "companyId"
        Required: False
plugins:
  - serverless-domain-manager
  - serverless-esbuild
  - serverless-cognito-add-custom-attributes
package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!node_modules/**"
    - "src/**"
    - "package.json"
functions:
  createUser:
    handler: src/handler/CreateUserHandler.HANDLER
    events:
      - httpApi:
          path: /create
          method: post
  addCustomClaims:
    handler: src/handler/AddCustomClaimsHandler.HANDLER
resources:
  Resources:
    LogisUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-logis-user
        #        UsernameAttributes: // Allow only login with email
        #          - email
        UserPoolTier: ESSENTIALS
        LambdaConfig:
          PreTokenGenerationConfig:
            LambdaArn: ${self:custom.resources.customClaimsArn}
            LambdaVersion: V2_0
        AliasAttributes:
          - email
          - preferred_username
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: False
            Mutable: True
            Name: "given_name"
            Required: True
          - AttributeDataType: String
            DeveloperOnlyAttribute: False
            Mutable: True
            Name: "family_name"
            Required: True
          - AttributeDataType: String
            DeveloperOnlyAttribute: False
            Mutable: True
            Name: "gender"
            Required: False
          - AttributeDataType: String
            DeveloperOnlyAttribute: False
            Mutable: True
            Name: "phone_number"
            Required: True
          - AttributeDataType: String
            DeveloperOnlyAttribute: False
            Mutable: True
            Name: "birthdate"
            Required: False
        AutoVerifiedAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: False
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: True
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: True
            TemporaryPasswordValidityDays: 7
        EmailConfiguration:
          EmailSendingAccount: "DEVELOPER"
          From: ${self:custom.resources.fromEmail}
          SourceArn: ${self:custom.resources.emailSesArn}
        AdminCreateUserConfig:
          InviteMessageTemplate:
            EmailMessage: "Bienvenido a LogiS su nombre de usuario es {username} y su contraseña temporal es {####} en la aplicación podrá asignar una nueva contraseña."
            EmailSubject: "Contraseña temporal de acceso a la aplicación Logis"
            SMSMessage: "Bienvenido a LogiS su nombre de usuario es {username} y su contraseña temporal es {####}"
        VerificationMessageTemplate:
          DefaultEmailOption: "CONFIRM_WITH_CODE"
          EmailMessage: "El código para ingresar a la aplicación LogiS es: {####}"
          EmailSubject: "Su código de verificación"
          SmsMessage: "Su código de verificación para la aplicación LogiS es: {####}"
    LogisPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}_${self:provider.stage}-client
        UserPoolId:
          Ref: LogisUserPool
        GenerateSecret: False
        TokenValidityUnits:
          AccessToken: "minutes"
          IdToken: "minutes"
          RefreshToken: "days"
        AccessTokenValidity: 30
        RefreshTokenValidity: 1
        IdTokenValidity: 30
        AllowedOAuthFlows:
          - "implicit"
        AllowedOAuthFlowsUserPoolClient: True
        AllowedOAuthScopes:
          - "phone"
          - "email"
          - "openid"
          - "profile"
          - "aws.cognito.signin.user.admin"
        ExplicitAuthFlows:
          - "ALLOW_ADMIN_USER_PASSWORD_AUTH"
          - "ALLOW_CUSTOM_AUTH"
          - "ALLOW_USER_PASSWORD_AUTH"
          - "ALLOW_USER_SRP_AUTH"
          - "ALLOW_REFRESH_TOKEN_AUTH"
        CallbackURLs:
          - "http://localhost:3000"
        EnableTokenRevocation: False
        PreventUserExistenceErrors: "ENABLED"
        SupportedIdentityProviders:
          - "COGNITO"
        ReadAttributes:
          - "given_name"
          - "email"
          - "family_name"
          - "gender"
          - "phone_number"
          - "birthdate"
        WriteAttributes:
          - "given_name"
          - "family_name"
          - "gender"
          - "phone_number"
          - "birthdate"
    AdminUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "Admin"
        UserPoolId:
          Ref: LogisUserPool
    LogisticsCoordinatorUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "LogisticsCoordinator"
        UserPoolId:
          Ref: LogisUserPool
    CompanyManagerUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "CompanyManager"
        UserPoolId:
          Ref: LogisUserPool
    SalesManagerUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "SalesManager"
        UserPoolId:
          Ref: LogisUserPool
    SiteEngineerUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "SiteEngineer"
        UserPoolId:
          Ref: LogisUserPool
    SiteManagerUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "SiteManager"
        UserPoolId:
          Ref: LogisUserPool
    LogisDomainPool:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        #        CustomDomainConfig:
        #          CertificateArn: ${ssm:${self:custom.prefix}/CERTIFICATE_ARN}
        #        Domain: "auth.logis.tmetsoft.com"
        Domain: ${self:provider.stage}-logis-user
        UserPoolId:
          Ref: LogisUserPool
    OnAddClaimsCognitoPermission:
      Type: 'AWS::Lambda::Permission'
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName: ${self:custom.resources.customClaimsArn}
        Principal: "cognito-idp.amazonaws.com"
        SourceArn:
          Fn::Join:
              - ""
              - - "arn:aws:cognito-idp:us-east-1:"
                - "Ref": "AWS::AccountId"
                - ":userpool/"
                - "Ref": "LogisUserPool"
  Outputs:
    LogisUserPoolId:
      Value:
        Ref: LogisUserPool
    LogisUserClientId:
      Value:
        Ref: LogisPoolClient