/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserCommonProps {
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  /**
   * @minItems 1
   */
  phoneNumbers: [Phone, ...Phone[]];
  gender: "M" | "F";
  birthday: number;
  addresses: Address[];
  picture?: string;
  profileCompleted: boolean;
  status?: "A" | "I";
}
export interface Phone {
  type?: "MOBILE" | "HOME" | "OTHER";
  number?: string;
}
export interface Address {
  type?: "HOME" | "WORK" | "OTHER";
  country: string;
  province: string;
  city: string;
  zipCode?: string;
  principalStreet?: string;
  secondaryStreet?: string;
  number?: string;
  reference?: string;
  isComplete: boolean;
}
