/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserProfile {
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: Phone;
  gender?: "male" | "female";
  birthdate: number;
  companyId?: string;
  status: "active" | "inactive";
  role: "Admin" | "LogisticsCoordinator" | "CompanyManager" | "SalesManager" | "SiteEngineer" | "SiteManager";
}
export interface Phone {
  type?: "MOBILE" | "HOME" | "OTHER";
  number?: string;
}
